"""Add_order_field_to_BlogImage

Revision ID: 85696b1c3b4c
Revises: bb996ebc499d
Create Date: 2024-05-31 18:41:07.768581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85696b1c3b4c'
down_revision = 'bb996ebc499d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_image', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
