"""blog_date_default

Revision ID: dda1d1b7f2e4
Revises: 701f62d73de5
Create Date: 2024-05-06 17:12:48.830230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda1d1b7f2e4'
down_revision = '701f62d73de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('pub_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('pub_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
