version: '3.8'

services:

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      # - pg_data:/var/lib/postgresql/
      - ./database/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: ./
    restart: always
    volumes:
      - static_data:/app/victoria_site/static
      # - ./victoria_site/static/media:/app/victoria_site/static/media
      # - ./victoria_site/static/user_images:/app/victoria_site/static/user_images
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    command: gunicorn --bind 0.0.0.0:5000 run:app
    ports:
      - 5000:5000

  nginx:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/backend_static
      # - ./victoria_site/static:/backend_static
      # - ./victoria_site/static/media:/backend_static/media
      # - ./victoria_site/static/user_images:/backend_static/user_images
    depends_on:
      - backend
    restart: always

volumes:
  pg_data:
  static_data:
  # media_data:
