"""blog_date_not_nullable

Revision ID: 701f62d73de5
Revises: 81217a8a2968
Create Date: 2024-05-06 16:30:09.514448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701f62d73de5'
down_revision = '81217a8a2968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('pub_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('pub_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
