"""delete_blog

Revision ID: 7f562bb9f639
Revises: dda1d1b7f2e4
Create Date: 2024-05-07 22:50:31.557590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f562bb9f639'
down_revision = 'dda1d1b7f2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('image', sa.VARCHAR(length=256), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('pub_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pub_date'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###
