"""Add_admin_model

Revision ID: 7fb637e8fce0
Revises: 85696b1c3b4c
Create Date: 2024-06-04 16:14:40.544080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb637e8fce0'
down_revision = '85696b1c3b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_image', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('label', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('instagram_link', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('behance_link', sa.String(length=256), nullable=True))
        batch_op.drop_column('instagram')
        batch_op.drop_column('behance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('behance', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('behance_link')
        batch_op.drop_column('instagram_link')
        batch_op.drop_column('label')
        batch_op.drop_column('artist_name')

    with op.batch_alter_table('blog_image', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###
