"""tags_slug_removed

Revision ID: 81217a8a2968
Revises: c697150415d4
Create Date: 2024-05-03 11:33:26.214632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81217a8a2968'
down_revision = 'c697150415d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
