"""Add_order_field_to_ProjectImage

Revision ID: bb996ebc499d
Revises: 9a5bce7c6bd0
Create Date: 2024-05-31 11:49:19.531128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb996ebc499d'
down_revision = '9a5bce7c6bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_image', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
