FROM nginx

# COPY nginx.conf /etc/nginx/templates/default.conf
# COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY nginx.conf /etc/nginx/nginx.conf
- ./nginx.conf:/etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/conf.d